//
//  CountryFlag.swift
//  PhoenixFootballApp
//
//  Created by Shahanul Haque on 7/12/25.
//

class CountryFlagMap {
    // Move the large initial flag map to a private extension
   static var initialFlagMap: [String: String] {
        [
            "Saudi-Arabia":"https://flagcdn.com/w320/sa.png",
            "San-Marino":"https://flagcdn.com/w320/sm.png",
            "Northern-Ireland":"https://flagcdn.com/w320/gb.png",
            "New-Zealand":"https://flagcdn.com/w320/nz.png",
            "United-Arab-Emirates":"https://flagcdn.com/w320/ae.png",
            
            "South-Africa":"https://flagcdn.com/w320/za.png",
            "South-Korea":"https://flagcdn.com/w320/kr.png",
            "Costa-Rica":"https://flagcdn.com/w320/cr.png",
//            "Congo-DR":"https://media.api-sports.io/flags/cg.svg",
//            "Chinese-Taipei":"https://media.api-sports.io/flags/tw.svg",
            "Burkina-Faso":"https://flagcdn.com/w320/bf.png",
            
            "Albania": "https://flagcdn.com/w320/al.png",
            "Gabon": "https://flagcdn.com/w320/ga.png",
            "Guadeloupe": "https://flagcdn.com/w320/gp.png",
            "Grenada": "https://flagcdn.com/w320/gd.png",
            "Japan": "https://flagcdn.com/w320/jp.png",
            "Colombia": "https://flagcdn.com/w320/co.png",
            "USA": "https://flagcdn.com/w320/us.png",
            "Malaysia": "https://flagcdn.com/w320/my.png",
            "Turkey": "https://flagcdn.com/w320/tr.png",
            "Cameroon": "https://flagcdn.com/w320/cm.png",
            "Palestine": "https://flagcdn.com/w320/ps.png",
            "France": "https://flagcdn.com/w320/fr.png",
            "Nicaragua": "https://flagcdn.com/w320/ni.png",
            "Trinidad-And-Tobago": "https://flagcdn.com/w320/tt.png",
            "Italy": "https://flagcdn.com/w320/it.png",
            "Israel": "https://flagcdn.com/w320/il.png",
            "Iran": "https://flagcdn.com/w320/ir.png",
            "Thailand": "https://flagcdn.com/w320/th.png",
            "Syria": "https://flagcdn.com/w320/sy.png",
            "Ethiopia": "https://flagcdn.com/w320/et.png",
            "Oman": "https://flagcdn.com/w320/om.png",
            "Chinese‑Taipei": "https://flagcdn.com/w320/tw.png",
            "Kenya": "https://flagcdn.com/w320/ke.png",
            "Faroe‑Islands": "https://flagcdn.com/w320/fo.png",
            "Mongolia": "https://flagcdn.com/w320/mn.png",
            "Nigeria": "https://flagcdn.com/w320/ng.png",
            "Venezuela": "https://flagcdn.com/w320/ve.png",
            "Pakistan": "https://flagcdn.com/w320/pk.png",
            "Dominican‑Republic": "https://flagcdn.com/w320/do.png",
            "Australia": "https://flagcdn.com/w320/au.png",
            "Peru": "https://flagcdn.com/w320/pe.png",
            "Hong‑Kong": "https://flagcdn.com/w320/hk.png",
            "Congo": "https://flagcdn.com/w320/cd.png",
            "Ecuador": "https://flagcdn.com/w320/ec.png",
            "Sweden": "https://flagcdn.com/w320/se.png",
            "Belize": "https://flagcdn.com/w320/bz.png",
            "Jordan": "https://flagcdn.com/w320/jo.png",
            "Antigua‑And‑Barbuda": "https://flagcdn.com/w320/ag.png",
            "Bosnia": "https://flagcdn.com/w320/ba.png",
            "Bolivia": "https://flagcdn.com/w320/bo.png",
            "Slovakia": "https://flagcdn.com/w320/sk.png",
            "Senegal": "https://flagcdn.com/w320/sn.png",
            "Tajikistan": "https://flagcdn.com/w320/tj.png",
            "Belarus": "https://flagcdn.com/w320/by.png",
            "Canada": "https://flagcdn.com/w320/ca.png",
            "Iceland": "https://flagcdn.com/w320/is.png",
            "India": "https://flagcdn.com/w320/in.png",
            "Croatia": "https://flagcdn.com/w320/hr.png",
            "New‑Zealand": "https://flagcdn.com/w320/nz.png",
            "Wales": "https://flagcdn.com/w320/gb-wls.png",
            "Finland": "https://flagcdn.com/w320/fi.png",
            "Spain": "https://flagcdn.com/w320/es.png",
            "Vietnam": "https://flagcdn.com/w320/vn.png",
            "Switzerland": "https://flagcdn.com/w320/ch.png",
            "Malta": "https://flagcdn.com/w320/mt.png",
            "China": "https://flagcdn.com/w320/cn.png",
            "South‑Africa": "https://flagcdn.com/w320/za.png",
            "Georgia": "https://flagcdn.com/w320/ge.png",
            "Mauritius": "https://flagcdn.com/w320/mu.png",
            "Germany": "https://flagcdn.com/w320/de.png",
            "Guinea": "https://flagcdn.com/w320/gn.png",
            "Norway": "https://flagcdn.com/w320/no.png",
            "Kuwait": "https://flagcdn.com/w320/kw.png",
            "Czech‑Republic": "https://flagcdn.com/w320/cz.png",
            "Armenia": "https://flagcdn.com/w320/am.png",
            "Myanmar": "https://flagcdn.com/w320/mm.png",
            "Fiji": "https://flagcdn.com/w320/fj.png",
            "San‑Marino": "https://flagcdn.com/w320/sm.png",
            "Bhutan": "https://flagcdn.com/w320/bt.png",
            "Philippines": "https://flagcdn.com/w320/ph.png",
            "Rwanda": "https://flagcdn.com/w320/rw.png",
            "Ivory‑Coast": "https://flagcdn.com/w320/ci.png",
            "Andorra": "https://flagcdn.com/w320/ad.png",
            "Lithuania": "https://flagcdn.com/w320/lt.png",
            "Argentina": "https://flagcdn.com/w320/ar.png",
            "Panama": "https://flagcdn.com/w320/pa.png",
            "Barbados": "https://flagcdn.com/w320/bb.png",
            "Northern‑Ireland": "https://flagcdn.com/w320/gb-nir.png",
            "Morocco": "https://flagcdn.com/w320/ma.png",
            "Lesotho": "https://flagcdn.com/w320/ls.png",
            "Malawi": "https://flagcdn.com/w320/mw.png",
            "Montenegro": "https://flagcdn.com/w320/me.png",
            "England": "https://flagcdn.com/w320/gb-eng.png",
            "Botswana": "https://flagcdn.com/w320/bw.png",
            "Nepal": "https://flagcdn.com/w320/np.png",
            "Algeria": "https://flagcdn.com/w320/dz.png",
            "Burkina‑Faso": "https://flagcdn.com/w320/bf.png",
            "Zimbabwe": "https://flagcdn.com/w320/zw.png",
            "Indonesia": "https://flagcdn.com/w320/id.png",
            "Honduras": "https://flagcdn.com/w320/hn.png",
            "Togo": "https://flagcdn.com/w320/tg.png",
            "Latvia": "https://flagcdn.com/w320/lv.png",
            "Hungary": "https://flagcdn.com/w320/hu.png",
            "Scotland": "https://flagcdn.com/w320/gb-sct.png",
            "El‑Salvador": "https://flagcdn.com/w320/sv.png",
            "Bangladesh": "https://flagcdn.com/w320/bd.png",
            "Guatemala": "https://flagcdn.com/w320/gt.png",
            "Estonia": "https://flagcdn.com/w320/ee.png",
            "Macedonia": "https://flagcdn.com/w320/mk.png",
            "Gambia": "https://flagcdn.com/w320/gm.png",
            "Iraq": "https://flagcdn.com/w320/iq.png",
            "Mali": "https://flagcdn.com/w320/ml.png",
            "Poland": "https://flagcdn.com/w320/pl.png",
            "Ukraine": "https://flagcdn.com/w320/ua.png",
            "Curacao": "https://flagcdn.com/w320/cw.png",
            "Jamaica": "https://flagcdn.com/w320/jm.png",
            "Romania": "https://flagcdn.com/w320/ro.png",
            "Azerbaijan": "https://flagcdn.com/w320/az.png",
            "Uganda": "https://flagcdn.com/w320/ug.png",
            "Kosovo": "https://flagcdn.com/w320/xk.png",
            "Tunisia": "https://flagcdn.com/w320/tn.png",
            "Ghana": "https://flagcdn.com/w320/gh.png",
            "Congo‑DR": "https://flagcdn.com/w320/cg.png",
            "Serbia": "https://flagcdn.com/w320/rs.png",
            "Kyrgyzstan": "https://flagcdn.com/w320/kg.png",
            "Cyprus": "https://flagcdn.com/w320/cy.png",
            "Turkmenistan": "https://flagcdn.com/w320/tm.png",
            "Singapore": "https://flagcdn.com/w320/sg.png",
            "Ireland": "https://flagcdn.com/w320/ie.png",
            "Bermuda": "https://flagcdn.com/w320/bm.png",
            "Saudi‑Arabia": "https://flagcdn.com/w320/sa.png",
            "South‑Korea": "https://flagcdn.com/w320/kr.png",
            "Egypt": "https://flagcdn.com/w320/eg.png",
            "Bahrain": "https://flagcdn.com/w320/bh.png",
            "Angola": "https://flagcdn.com/w320/ao.png",
            "Greece": "https://flagcdn.com/w320/gr.png",
            "Costa‑Rica": "https://flagcdn.com/w320/cr.png",
            "Netherlands": "https://flagcdn.com/w320/nl.png",
            "Portugal": "https://flagcdn.com/w320/pt.png",
            "Eswatini": "https://flagcdn.com/w320/sz.png",
            "Laos": "https://flagcdn.com/w320/la.png",
            "Luxembourg": "https://flagcdn.com/w320/lu.png",
            "Macao": "https://flagcdn.com/w320/mo.png",
            "Yemen": "https://flagcdn.com/w320/ye.png",
            "Haiti": "https://flagcdn.com/w320/ht.png",
            "Uzbekistan": "https://flagcdn.com/w320/uz.png",
            "Liberia": "https://flagcdn.com/w320/lr.png",
            "Somalia": "https://flagcdn.com/w320/so.png",
            "Bulgaria": "https://flagcdn.com/w320/bg.png",
            "Zambia": "https://flagcdn.com/w320/zm.png",
            "Maldives": "https://flagcdn.com/w320/mv.png",
            "United‑Arab‑Emirates": "https://flagcdn.com/w320/ae.png",
            "Brazil": "https://flagcdn.com/w320/br.png",
            "Aruba": "https://flagcdn.com/w320/aw.png",
            "Mexico": "https://flagcdn.com/w320/mx.png",
            "Austria": "https://flagcdn.com/w320/at.png",
            "Kazakhstan": "https://flagcdn.com/w320/kz.png",
            "Lebanon": "https://flagcdn.com/w320/lb.png",
            "Cambodia": "https://flagcdn.com/w320/kh.png",
            "Qatar": "https://flagcdn.com/w320/qa.png",
            "Denmark": "https://flagcdn.com/w320/dk.png",
            "Libya": "https://flagcdn.com/w320/ly.png",
            "Liechtenstein": "https://flagcdn.com/w320/li.png",
            "Paraguay": "https://flagcdn.com/w320/py.png",
            "Belgium": "https://flagcdn.com/w320/be.png",
            "Russia": "https://flagcdn.com/w320/ru.png",
            "Namibia": "https://flagcdn.com/w320/na.png",
            "Burundi": "https://flagcdn.com/w320/bi.png",
            "Crimea": "https://flagcdn.com/w320/ua.png", // disputed territory
            "Uruguay": "https://flagcdn.com/w320/uy.png",
            "Mauritania": "https://flagcdn.com/w320/mr.png",
            "Benin": "https://flagcdn.com/w320/bj.png",
            "Gibraltar": "https://flagcdn.com/w320/gi.png",
            "Tanzania": "https://flagcdn.com/w320/tz.png",
            "Cuba": "https://flagcdn.com/w320/cu.png",
            "Moldova": "https://flagcdn.com/w320/md.png",
            "Sudan": "https://flagcdn.com/w320/sd.png",
            "Suriname": "https://flagcdn.com/w320/sr.png",
            "Slovenia": "https://flagcdn.com/w320/si.png",
            "Chile": "https://flagcdn.com/w320/cl.png"
        ]
    }
}
